version: '3'
services:
  backend:
    build: './backend/'
    ports:
      - 3001:3001
    networks:
      - backend
      - frontend
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: './frontend'
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
networks:
  backend:
  frontend:
