on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install back-end modules
        run: cd backend && npm install

      - name: Install front-end modules
        run: cd frontend && npm install

      - name: Run linter on backend
        run: cd backend && npm run lint
      
      - name: Run linter on frontend
        run: cd frontend && npm run lint

  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install front-end modules
        run: cd frontend && npm install

      - name: Run linter on frontend
        run: cd frontend && npm run lint:styles